// Command genfixedshift copies a compressor function and makes its hash shift constant.
// A constant shift frees the CL register in hot loops.
// The source function must contain one "shift := ..." statement.
// Run this command through go generate in internal/encoder.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
)

func main() {
	in := flag.String("in", "", "source file")
	out := flag.String("out", "", "generated file")
	srcFunc := flag.String("func", "", "source function")
	dstFunc := flag.String("name", "", "generated function")
	tableBits := flag.Int("bits", 0, "hash table bits")
	flag.Parse()
	if *in == "" || *out == "" || *srcFunc == "" || *dstFunc == "" || *tableBits <= 0 {
		log.Fatal("set -in, -out, -func, -name, and a positive -bits")
	}

	code, err := generate(*in, *srcFunc, *dstFunc, *tableBits)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, code, 0o644); err != nil {
		log.Fatal(err)
	}
}

func generate(path, srcFunc, dstFunc string, tableBits int) ([]byte, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, src, 0)
	if err != nil {
		return nil, err
	}

	var fn *ast.FuncDecl
	for _, d := range f.Decls {
		if d, ok := d.(*ast.FuncDecl); ok && d.Name.Name == srcFunc {
			fn = d
		}
	}
	if fn == nil {
		return nil, fmt.Errorf("%s: func %s not found", path, srcFunc)
	}
	shift, err := shiftStmt(fn)
	if err != nil {
		return nil, fmt.Errorf("%s: %s: %w", path, srcFunc, err)
	}

	off := func(p token.Pos) int { return fset.Position(p).Offset }
	var body strings.Builder
	body.Write(src[off(fn.Pos()):off(fn.Name.Pos())])
	body.WriteString(dstFunc)
	body.Write(src[off(fn.Name.End()):off(shift.Pos())])
	fmt.Fprintf(&body, "const shift = 64 - %d", tableBits)
	body.Write(src[off(shift.End()):off(fn.End())])

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by cmd/genfixedshift; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", f.Name.Name)
	b.WriteString(imports(f, fn))
	fmt.Fprintf(&b, "// %s implements %s with a constant hash shift for the %d-bit table.\n", dstFunc, srcFunc, tableBits)
	b.WriteString(body.String())
	b.WriteString("\n")
	return format.Source(b.Bytes())
}

// shiftStmt returns the only "shift := ..." statement in fn.
func shiftStmt(fn *ast.FuncDecl) (*ast.AssignStmt, error) {
	var found []*ast.AssignStmt
	ast.Inspect(fn.Body, func(n ast.Node) bool {
		a, ok := n.(*ast.AssignStmt)
		if ok && a.Tok == token.DEFINE && len(a.Lhs) == 1 {
			if id, ok := a.Lhs[0].(*ast.Ident); ok && id.Name == "shift" {
				found = append(found, a)
			}
		}
		return true
	})
	if len(found) != 1 {
		return nil, fmt.Errorf(`found %d "shift :=" statements, want 1`, len(found))
	}
	return found[0], nil
}

// imports returns an import block with the packages that fn uses.
func imports(f *ast.File, fn *ast.FuncDecl) string {
	used := map[string]bool{}
	ast.Inspect(fn, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if id, ok := sel.X.(*ast.Ident); ok {
				used[id.Name] = true
			}
		}
		return true
	})
	var b strings.Builder
	b.WriteString("import (\n")
	for _, imp := range f.Imports {
		path := strings.Trim(imp.Path.Value, `"`)
		name := path[strings.LastIndex(path, "/")+1:]
		if imp.Name != nil {
			name = imp.Name.Name
		}
		if used[name] {
			fmt.Fprintf(&b, "\t%s\n", imp.Path.Value)
		}
	}
	b.WriteString(")\n\n")
	return b.String()
}
