// Generate writeCommandsTable15 from writeCommandsAnyTable in
// compress_fragment_fast.go.
//
// The 15-bit table has a constant hash shift. Large inputs use this table.
//
// Run go generate from internal/encoder.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
)

const (
	srcFunc = "writeCommandsAnyTable"
	dstFunc = "writeCommandsTable15"
	srcVar  = "\tshift := c.shift\n"
	dstVar  = "\tconst shift = 64 - 15\n"
)

func main() {
	in := flag.String("in", "compress_fragment_fast.go", "source file")
	out := flag.String("out", "compress_fragment_fast_table15.go", "generated file")
	flag.Parse()

	code, err := generate(*in)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, code, 0o644); err != nil {
		log.Fatal(err)
	}
}

func generate(path string) ([]byte, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, src, 0)
	if err != nil {
		return nil, err
	}

	var body string
	var fn *ast.FuncDecl
	for _, d := range f.Decls {
		if d, ok := d.(*ast.FuncDecl); ok && d.Name.Name == srcFunc {
			fn = d
			body = string(src[fset.Position(d.Pos()).Offset:fset.Position(d.End()).Offset])
		}
	}
	if fn == nil {
		return nil, fmt.Errorf("%s: func %s not found", path, srcFunc)
	}
	for _, s := range []string{srcFunc, srcVar} {
		if n := strings.Count(body, s); n != 1 {
			return nil, fmt.Errorf("%s: %q found %d times in %s, want 1", path, s, n, srcFunc)
		}
	}
	body = strings.Replace(body, srcFunc, dstFunc, 1)
	body = strings.Replace(body, srcVar, dstVar, 1)

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by cmd/gencommands15; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", f.Name.Name)
	b.WriteString(imports(f, fn))
	fmt.Fprintf(&b, "// %s uses a constant hash shift for the 15-bit table.\n", dstFunc)
	b.WriteString(body)
	b.WriteString("\n")
	return format.Source(b.Bytes())
}

// imports returns an import block with the packages that fn uses.
func imports(f *ast.File, fn *ast.FuncDecl) string {
	used := map[string]bool{}
	ast.Inspect(fn, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if id, ok := sel.X.(*ast.Ident); ok {
				used[id.Name] = true
			}
		}
		return true
	})
	var b strings.Builder
	b.WriteString("import (\n")
	for _, imp := range f.Imports {
		path := strings.Trim(imp.Path.Value, `"`)
		name := path[strings.LastIndex(path, "/")+1:]
		if imp.Name != nil {
			name = imp.Name.Name
		}
		if used[name] {
			fmt.Fprintf(&b, "\t%s\n", imp.Path.Value)
		}
	}
	b.WriteString(")\n\n")
	return b.String()
}
