// Code generated by cmd/genfixedshift; DO NOT EDIT.

package encoder

import (
	"math/bits"
	"unsafe"
)

// createCommandsTable17 implements createCommandsMinMatch6 with a constant hash shift for the 17-bit table.
func (c *twoPassCompressor) createCommandsTable17(
	input []byte, pos, blockSize, inputSize int,
	commands []uint32, literals []byte,
) (numCommands, numLiterals int) {
	const minMatch = 6

	cmdHisto := &c.arena.cmdHisto
	ip := pos
	const shift = 64 - 17
	ipEnd := pos + blockSize
	nextEmit := pos
	lastDistance := -1
	tbl := unsafe.Pointer(unsafe.SliceData(c.table))
	cmdPos := 0
	litPos := 0

	if blockSize < inputMarginBytes {
		goto encodeRemainder
	}

	{
		// For the last block, keep a 16-byte margin so all distances are at
		// most window size - 16. For other blocks, keep a margin of minMatch
		// bytes so we don't go past the block size with a copy.
		lenLimit := min(blockSize-minMatch, inputSize-inputMarginBytes)
		ipLimit := pos + lenLimit

		ip++

		for {
			var candidate int
			var found bool
			ip, candidate, found = findMatchMinMatch6(input, tbl, ip, ipLimit, lastDistance, shift)
			if !found {
				goto encodeRemainder
			}

			// Step 2: Emit the found match together with the literal bytes from
			// nextEmit, and then see if we can find a next match immediately
			// afterwards.
			{
				base := ip
				matched := minMatch + matchLenAt(
					input, uint(candidate+minMatch), uint(ip+minMatch), ipEnd-ip-minMatch)
				distance := base - candidate
				insert := base - nextEmit
				ip += matched

				if u := uint(insert); u < 130 {
					cmd := insertLenCodeQ1Small[u]
					commands[cmdPos] = cmd
					cmdHisto[cmd&0x7F]++
					cmdPos++
				} else {
					cmdPos += encodeInsertLen(commands[cmdPos:], u, cmdHisto)
				}
				// The scan margin makes the 16-byte source read safe.
				if insert <= 16 && litPos+16 <= len(literals) {
					copy16(literals, uint(litPos), input, uint(nextEmit))
				} else {
					copy(literals[litPos:], input[nextEmit:nextEmit+insert])
				}
				litPos += insert
				if distance == lastDistance {
					commands[cmdPos] = 64
					cmdHisto[64]++
					cmdPos++
				} else {
					cmdPos += encodeDistance(commands[cmdPos:], uint(distance), cmdHisto)
					lastDistance = distance
				}
				if cl := uint(matched); cl < 72 {
					cmd := copyLenLastDistanceCodeQ1Small[cl]
					commands[cmdPos] = cmd
					cmdHisto[cmd&0x7F]++
					cmdPos++
				} else {
					cmdPos += encodeCopyLenLastDistance(commands[cmdPos:], cl, cmdHisto)
				}
			}

			// Try to find another match immediately.
			for {
				nextEmit = ip
				if ip >= ipLimit {
					goto encodeRemainder
				}

				lo := loadU64LE(input, uint(ip-5))
				hi := loadU64LE(input, uint(ip-2))
				*(*uint32)(unsafe.Add(tbl, uintptr(hashBytesAtOffsetTwoPass6(lo, 0, shift))*4)) = uint32(ip - 5)
				*(*uint32)(unsafe.Add(tbl, uintptr(hashBytesAtOffsetTwoPass6(lo, 1, shift))*4)) = uint32(ip - 4)
				*(*uint32)(unsafe.Add(tbl, uintptr(hashBytesAtOffsetTwoPass6(lo, 2, shift))*4)) = uint32(ip - 3)
				*(*uint32)(unsafe.Add(tbl, uintptr(hashBytesAtOffsetTwoPass6(hi, 0, shift))*4)) = uint32(ip - 2)
				*(*uint32)(unsafe.Add(tbl, uintptr(hashBytesAtOffsetTwoPass6(hi, 1, shift))*4)) = uint32(ip - 1)
				curPtr := (*uint32)(unsafe.Add(tbl, uintptr(hashBytesAtOffsetTwoPass6(hi, 2, shift))*4))
				candidate = int(*curPtr)
				*curPtr = uint32(ip)
				if ip-candidate > maxDistance || (loadU64LE(input, uint(candidate))^(hi>>16))<<16 != 0 {
					break
				}

				base := ip
				matched := minMatch + matchLenAt(
					input, uint(candidate+minMatch), uint(ip+minMatch), ipEnd-ip-minMatch)
				ip += matched
				lastDistance = base - candidate

				// Fast path for cl < 134 (the dominant range on real corpora):
				// one table load delivers both the command word and ccode,
				// replacing the bits.Len + shift chain.
				var ccode uint
				if cl := uint(matched); cl < 134 {
					cmd := copyLenCodeQ1Small[cl]
					commands[cmdPos] = cmd
					ccode = uint(cmd & 0x7F)
				} else if cl < 2118 {
					tail := cl - 70
					nbits := uint(bits.Len(tail)) - 1
					ccode = nbits + 52
					extra := tail - (1 << nbits)
					commands[cmdPos] = uint32(ccode) | uint32(extra)<<8
				} else {
					ccode = 63
					extra := cl - 2118
					commands[cmdPos] = uint32(ccode) | uint32(extra)<<8
				}
				cmdHisto[ccode]++
				cmdPos++

				cmdPos += encodeDistance(commands[cmdPos:], uint(lastDistance), cmdHisto)
			}

			ip++
		}
	} // close block scope for ipLimit, lenLimit

encodeRemainder:
	// Emit the remaining bytes as literals.
	if nextEmit < ipEnd {
		insert := ipEnd - nextEmit
		cmdPos += encodeInsertLen(commands[cmdPos:], uint(insert), cmdHisto)
		copy(literals[litPos:], input[nextEmit:ipEnd])
		litPos += insert
	}
	return cmdPos, litPos
}
