// Code generated by cmd/gencommands15; DO NOT EDIT.

package encoder

import (
	"math/bits"
	"unsafe"
)

// writeCommandsTable15 uses a constant hash shift for the 15-bit table.
func (c *fragmentCompressor) writeCommandsTable15() {
	// Initialize the command and distance histograms.
	c.arena.cmdHisto = cmdHistoSeed
	input := c.input
	tbl := unsafe.Pointer(unsafe.SliceData(c.table))
	ip := c.pos
	const shift = 64 - 15
	lastDistance := -1
	c.ipEnd = c.pos + c.blockSize

	if c.blockSize < inputMarginBytes {
		c.writeRemainder()
		return
	}

	// For the last block, keep a 16-byte margin so all distances are at
	// most window size - 16. For other blocks, keep a 5-byte margin.
	lenLimit := min(c.blockSize-minMatchLen, len(input)-c.pos-inputMarginBytes)
	ipLimit := c.pos + lenLimit

	ip++
	nextLoad := loadU64LE(input, uint(ip))
	nextHash := hashBytesAtOffset(nextLoad, 0, shift)

	for {
		// Step 1: Scan forward in the input looking for a 5-byte-long match.
		// If we find one whose distance is too large, keep scanning.
		skip := uint32(32)
		nextIP := ip
		var candidate int

		for {
			slot := (*uint32)(unsafe.Add(tbl, uintptr(nextHash)*4))
			ipBytes := nextLoad
			bytesBetweenHashLookups := skip >> 5
			skip++
			ip = nextIP
			nextIP = ip + int(bytesBetweenHashLookups)
			if nextIP > ipLimit {
				c.writeRemainder()
				return
			}
			nextLoad = loadU64LE(input, uint(nextIP))
			nextHash = hashBytesAtOffset(nextLoad, 0, shift)

			candidate = ip - lastDistance
			// uint(candidate) < uint(ip) folds the two-step `candidate >= 0 &&
			// candidate < ip` validity check into a single unsigned compare:
			// when candidate is negative (initial state) its unsigned form is
			// larger than uint(ip), so the compare fails.
			if uint(candidate) < uint(ip) && (loadU64LE(input, uint(candidate))^ipBytes)<<24 == 0 {
				*slot = uint32(ip)
				if ip-candidate <= maxDistance {
					break
				}
				continue
			}

			candidate = int(*slot)
			*slot = uint32(ip)
			if (loadU64LE(input, uint(candidate))^ipBytes)<<24 == 0 {
				if ip-candidate <= maxDistance {
					break
				}
				continue
			}
		}

		// Step 2: Emit the found match together with the literal bytes from
		// nextEmit to the bitstream, and then see if we can find a next match
		// immediately afterwards.
		{
			base := ip
			matched := 5 + matchLenAt(
				input, uint(candidate+5), uint(ip+5), c.ipEnd-ip-5)
			distance := base - candidate
			insert := uint(base - c.nextEmit)
			ip += matched

			switch {
			case insert < 6:
				code := insert + 40
				c.b.writeBits(uint(c.arena.cmdDepth[code]), uint64(c.arena.cmdBits[code]))
				c.arena.cmdHisto[code]++
			case insert < 6210:
				c.writeInsertLen(insert)
			case c.shouldUseUncompressedMode(insert):
				c.writeUncompressedMetaBlock(
					input[c.metablockStart:base], c.mlenPos-3)
				c.pos = base
				c.nextEmit = c.pos
				c.nextBlock()
				return
			default:
				c.writeLongInsertLen(insert)
			}
			c.writeLiterals(input[c.nextEmit : c.nextEmit+int(insert)])
			if distance == lastDistance {
				c.b.writeBits(uint(c.arena.cmdDepth[64]), uint64(c.arena.cmdBits[64]))
				c.arena.cmdHisto[64]++
				c.writeCopyLenLastDistance(uint(matched))
			} else {
				c.writeDistanceAndCopyLenLastDistance(uint(distance), uint(matched))
				lastDistance = distance
			}

			c.nextEmit = ip
			if ip >= ipLimit {
				c.writeRemainder()
				return
			}
		}

		// Try to find another match immediately. writeCopyAndDistance is
		// inlined here so the inner-repeat-match loop's hottest call site
		// avoids per-iteration prologue/epilogue overhead. The function is
		// otherwise too large to inline automatically (cost ~400 vs the
		// 80-instruction budget) yet it's the only caller.
		for {
			inputBytes := loadU64LE(input, uint(ip-3))
			prevHash := hashBytesAtOffset(inputBytes, 0, shift)
			curHash := hashBytesAtOffset(inputBytes, 3, shift)
			*(*uint32)(unsafe.Add(tbl, uintptr(prevHash)*4)) = uint32(ip - 3)
			prevHash = hashBytesAtOffset(inputBytes, 1, shift)
			*(*uint32)(unsafe.Add(tbl, uintptr(prevHash)*4)) = uint32(ip - 2)
			prevHash = hashBytesAtOffset(inputBytes, 2, shift)
			*(*uint32)(unsafe.Add(tbl, uintptr(prevHash)*4)) = uint32(ip - 1)
			curPtr := (*uint32)(unsafe.Add(tbl, uintptr(curHash)*4))
			candidate = int(*curPtr)
			*curPtr = uint32(ip)
			if !isMatch(input, uint(ip), uint(candidate)) {
				break
			}
			base := ip
			matched := 5 + matchLenAt(
				input, uint(candidate+5), uint(ip+5), c.ipEnd-ip-5)
			if ip-candidate > maxDistance {
				break
			}
			ip += matched
			lastDistance = base - candidate
			distance := uint(lastDistance)
			copyLen := uint(matched)
			if copyLen >= 134 {
				c.writeCopyLen(copyLen)
				c.writeDistance(distance)
			} else {
				depth := c.arena.cmdDepth[:]
				cmdBits := c.arena.cmdBits[:]
				histo := c.arena.cmdHisto[:]

				// Distance: 2*(nbits-1)+prefix+80 ∈ [80,111]; total ≤ 31 bits.
				dd := distance + 3
				dNbits := (uint(bits.Len(dd)) - 2) & 63
				dPrefix := (dd >> dNbits) & 1
				dOffset := (2 + dPrefix) << dNbits
				distcode := 2*(dNbits-1) + dPrefix + 80
				dDepth := uint(depth[distcode]) & 63
				dBits := uint64(cmdBits[distcode]) | uint64(dd-dOffset)<<dDepth
				dLen := dDepth + dNbits

				// Copy length: lookup precomputed (ccode, nbits, cextra) so the
				// hot path is one table load + one depth/bits load instead of
				// the bits.Len + shift sequence (frees CL across the block).
				info := copyLenCodeInfo[copyLen]
				ccode := uint(info & 0xFF)
				nbits := uint((info >> 8) & 0xFF)
				cextra := uint(info >> 16)
				d := uint(depth[ccode]) & 63
				cBits := uint64(cmdBits[ccode]) | uint64(cextra)<<d
				cLen := d + nbits

				// Combined ≤ 51 bits, safely under the 56-bit writeBits limit.
				c.b.writeBits(cLen+dLen, cBits|dBits<<(cLen&63))
				histo[ccode]++
				histo[distcode]++
			}

			c.nextEmit = ip
			if ip >= ipLimit {
				c.writeRemainder()
				return
			}
		}

		ip++
		nextLoad = loadU64LE(input, uint(ip))
		nextHash = hashBytesAtOffset(nextLoad, 0, shift)
	}
}
